import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import logo from "../../public/images/zw_homepage2.png";
import Link from "next/link";
import Layout from "@/src/components/Home/Layout";
import { TypeAnimation } from "react-type-animation";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Studio Zw</title>
        <meta name="description" content="Generated by next app" />
      </Head>
      <main className="flex items-center text-dark w-full dark:text-light min-h-screen">
        <Layout className="pt-0 tablet:p-20 sm:p-2 ">
          <div className="flex laptop:flex-row items-center justify-between w-full mobile:flex-col tablet:flex-col sm:flex-col">
            <div className="w-1/2 tablet:w-full">
              <Image
                src={logo}
                alt="Company logo"
                className="w-full h-auto tablet:inline-block tablet:w-full mobile:w-full sm:w-full"
                priority
                sizes="(max-width: 768px) 100vw,
               (max-width:1200px) 50vw, 50vw"
              />
            </div>


            <div className="w-3/4 flex flex-col items-center self-center laptop:w-full laptop:text-center laptop:pt-3 tablet:pt-7 tablet:mx-10 mobile:pt-7 sm:pt-5  ">
              <h2 className="laptop:!text-8xl tablet:!text-4xl mobile:!text-xl font-extrabold ">
                <div className="mb-3 laptop:text-5xl sm:text-2xl"> Hi! I am</div>
              </h2>
              <div className="h-24 tablet:h-35 mobile:h-35 mobile:text-3xl tablet:text-5xl laptop:text-6xl sm:text-3xl ">
                <h2>
                  <TypeAnimation
                    sequence={[
                      // Same substring at the start will only be typed out once, initially
                      "Zhan Wen ",
                      1000, // wait 1s before replacing "Mice" with "Hamsters"
                      "A Software Developer ",
                      1000,
                      "A Problem solver ",
                      1000,
                      "A Team Player  ",
                      1000,
                    ]}
                    wrapper="span"
                    speed={50}
                    repeat={Infinity}
                    className="mobile:!text-3xl tablet:!text-5xl laptop:text-6xl m-2 flex items-center justify-center text-center text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600"
                  />
                </h2>
              </div>

              <p className=" flex items-center justify-center text-center px-4 ">
                Software Enthusiast • Builder of Cool Things • Lifelong Debugger
                <br /><br />
                Welcome to my little slice of the web — part resume, part portfolio, and 100% me.
                <br />
                I enjoy bringing ideas to life with code, whether it’s crafting smooth user experiences
                or solving tricky backend problems.
                <br /><br />
                🚀 Explore my projects, scroll through my experiences, and if something catches your eye — let’s chat!
              </p>
              <div className="flex items-center self-center  mt-2 laptop:self-center  ">
                <Link
                  href="/Ng Zhan Wen Resume.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg border-white font-semibold hover:bg-white hover:text-black border-solid border-transparent hover:border-blackk border-2 dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base mx-5"
                  download={true}
                >
                  {" "}
                  View my Resume{" "}
                </Link>
                {/* <Link
                  href="mailto:wendy.wnd77@gmail.com"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg border-white font-semibold hover:bg-white hover:text-black border-solid border-transparent hover:border-blackk border-2 dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base mx-5"
                >
                  {" "}
                  Contact
                </Link> */}
              </div>
              {/* <div className="flex items-center self-center mt-10 lg:self-center ">
                <Link
                  href="https://buymeacoffee.com/callmewendy"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg border-white font-semibold hover:bg-white hover:text-black border-solid border-transparent hover:border-blackk border-2 dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base mx-5"
                >
                  Buy me a coffee &#128123;
                </Link>
              </div> */}
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
